spring.datasource.url=jdbc:postgresql://localhost:5432/orders
spring.datasource.username=admin
spring.datasource.password=P@ssw0rd123!
external.api.key=sample-api-key
spring.jpa.hibernate.ddl-auto=update

server.port=8080
